project:
  type: website

website:
  title: "G. Pardhu"
  google-analytics: "G-EGR7E28T14"
  description: "Welcome to the portfolio of Partha Sai Guttikonda, an innovative Computational Biologist and Full-Stack Engineer. Explore my work in machine learning, high-performance computing, medical imaging, and cloud infrastructure optimization. Let's collaborate and push the boundaries of technology!"
  image: "./images/profile.jpg"
  open-graph: true
  favicon: ./images/profile.jpg

  
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog
      - href: pubs.qmd
        text: Publications

    right: 
      - icon: linkedin
        href: https://www.linkedin.com/in/guttikonda-pardhu/
      - icon: github
        href: https://github.com/propardhu
      - icon: medium
        href: https://medium.com/@guttikondaparthasai
      # - icon: file-earmark-text
      #   text: CV
        # href: cv/index.qmd
  page-footer: "Developed with Quarto by Partha Sai Guttikonda — 2024" 
  reader-mode: false
format:
  html:
    theme: 
      light: [simplex, styles.scss]
      dark: [superhero, styles.scss]
    toc: true
    toc-location: left
execute:
  freeze: auto